### ISSUE TITLE
Recent ISBN is not properly hyphenated

### ISSUE THREAD

**Issue by clemlatz** [GitbookIO/isbn-utils#1]
If have this recent french ISBN : `9791091146135` that should converts, with hyphens, to : `979-10-91146-13-5`, but :

``` javascript
isbn.parse('9791091146135').asIsbn13(true)
```

gives me `979-1-09-114613-5`

The problem is that the library as it is is missing the three new groups for ISBNs starting with 979 (979-10 for France, 979-11 for Korea and 979-12 for Italy) and doesn't handle groups starting with 979.

I know how to fix this and have already done it in a similary ISBN javascript library, would you accept a pull request ?

**Comment by SamyPesse** [comment]
Yes, feel free to post a PR :)
